import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // 前ページ共通のレイアウトをかく
    <html lang="ja">
      <body className="container mx-auto bg-slate-700 text-slate-50">
        <div className="flex flex-col min-h-screen">
          <Header />
          {/* 子が読み込み完了するまでフォールバックを表示できる */}
          {/* <Suspense fallback={<Loading />}> */}
          <main className="flex-grow">{children}</main>
          {/* </Suspense> */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
